### ISSUE TITLE
Docker Swarm Command aka docker service [...]

### ISSUE THREAD

**Issue by pascalandy** [wsargent/docker-cheat-sheet#111]
Hi,

I'm looking for resources to migrate my compose v2 setup into `docker services ...` with some bash script to launch multiple docker cmd (build - push docker service).

Is documentation for Swarm in the roadmap ?
Cheers!

**Comment by collegeimprovements** [comment]
+1

**Comment by wsargent** [comment]
It's not in the roadmap -- this is just Docker without any service offerings, and it's still a huge undertaking to keep it up to date.  The docker networking section especially needs more filling out.

**Comment by pascalandy** [comment]
OK thanks!
