### ISSUE TITLE
Defective link

### ISSUE THREAD

**Issue by busti** [wsargent/docker-cheat-sheet#174]
The link to the DOCKERFILE tutorial in https://github.com/wsargent/docker-cheat-sheet#tutorial is defective.  
`http://flux7.com/blogs/docker/docker-tutorial-series-part-3-automation-is-the-word-using-dockerfile/` [link](http://flux7.com/blogs/docker/docker-tutorial-series-part-3-automation-is-the-word-using-dockerfile/)

**Comment by busti** [comment]
The new link is `https://www.flux7.com/tutorial/docker-tutorial-series-part-3-automation-is-the-word-using-dockerfile/`

**Comment by wsargent** [comment]
Can you submit a PR?

**Comment by busti** [comment]
Sure! It is #175 
Sorry, I was on my phone at the time.

**Comment by wsargent** [comment]
Fixed by #175
