### ISSUE TITLE
Port 80

### ISSUE THREAD

**Issue by akashnimare** [wsargent/docker-cheat-sheet#42]
I am using a grafana dokcer image. By default it runs at port 3000. How do I change it to 80

**Comment by veggiemonk** [comment]
A simple
```
docker run -d -p 80:3000 "replaceTheNameOfTheImagesHere"
```
should do. Isn't it?
Please read: https://docs.docker.com/userguide/dockerlinks/

**Comment by akashnimare** [comment]
and what if my graphite is running on port 80?
I used -p 8080:80 for graphite.
I want graphite to run port 3000 and grafana to 80.
Can you help me out for?

**Comment by veggiemonk** [comment]
Can you show your command, it is very difficult to know what you are talking about.

**Comment by akashnimare** [comment]
Here is the process I did
First I run graphite
>sudo docker run -d \
  --name graphite \
  -p 8080:80 \
  -p 2003:2003 \
  --restart="always" \
  -v /data/graphite/storage/whisper:/opt/graphite/storage/whisper  \
  sitespeedio/graphite

Then Grafana 
> sudo docker run -d -p 3000:3000 \
-v /data/grafana:/var/lib/grafana \
-e "GF_SECURITY_ADMIN_USER=myuser" \
-e "GF_SECURITY_ADMIN_PASSWORD=MY_SUPER_STRONG_PASSWORD" \
--name grafana \
--restart="always" \
grafana/grafana

My grafana is running on http://someipaddress:3000 but I want it to run on http://someipaddress

**Comment by veggiemonk** [comment]
sudo docker run -d -p **80**:3000 \
-v /data/grafana:/var/lib/grafana \
-e "GF_SECURITY_ADMIN_USER=myuser" \
-e "GF_SECURITY_ADMIN_PASSWORD=MY_SUPER_STRONG_PASSWORD" \
--name grafana \
--restart="always" \
grafana/grafana

**Comment by akashnimare** [comment]
Holyshit it's working.

Thanks a ton :)
