### ISSUE TITLE
Why do you say docker image ids are sensitive?

### ISSUE THREAD

**Issue by sleaze** [wsargent/docker-cheat-sheet#48]
I don't understand the sentiment behind:

    Docker image ids are sensitive information
    and should not be exposed to the outside
    world. Treat them like passwords.

This only seems to be the case when a public registry is being used.  If you agree, will you add a note stating as much?

**Comment by wsargent** [comment]
Hi there: see https://medium.com/@quayio/your-docker-image-ids-are-secrets-and-its-time-you-treated-them-that-way-f55e9f14c1a4 for the rationale.

**Comment by sleaze** [comment]
Weird.  OK THANKS ARGENT.
