### ISSUE TITLE
Exposing ports incorrect?

### ISSUE THREAD

**Issue by bfdill** [wsargent/docker-cheat-sheet#59]
I'm new to docker and appreciate the cheat-sheet.  I'm probably doing something wrong, but after fighting with EXPOSE, it seems the cheat-sheet is wrong.

Exposing ports says:
> If you don't want to use the -p option on the command line, you can persist port forwarding by using EXPOSE

But the [documents](https://docs.docker.com/engine/reference/builder/#expose) say:
> The EXPOSE instruction informs Docker that the container listens on the specified network ports at runtime. EXPOSE does not make the ports of the container accessible to the host. To do that, you must use either the -p flag to publish a range of ports or the -P flag to publish all of the exposed ports.

**Comment by tedyoung** [comment]
You're correct, the cheat-sheet *is* wrong here (I was just about to file a PR myself!) -- `EXPOSE` in a Dockerfile indicates that the port *could* be mapped, but won't be unless either ` -P ` or ` -p port:port ` is used from the command-line, or specified in something like `docker-compose.yml` for use with `docker-compose`.

**Comment by wsargent** [comment]
Whoops.

**Comment by wsargent** [comment]
@tedyoung @bfdill if you know what "docker network" does, I added a stub section but haven't worked with it myself.
