### ISSUE TITLE
make it exportable in PDF, htm with versioning

### ISSUE THREAD

**Issue by krishna81m** [wsargent/docker-cheat-sheet#81]
make it exportable in PDF, htm with versioning and include it in the repo so you can bookmark or save it.

**Comment by wsargent** [comment]
What?  No.  Find your favorite Markdown rendering and [print it to PDF](http://lmgtfy.com/?q=print+to+pdf) yourself.

**Comment by krishna81m** [comment]
Yeah, may be I asked too much, but not that I can't, it would be nice these links other than as github project page.

**Comment by rngtng** [comment]
what about a github page? should be a no-brainer with jekyll?

**Comment by wsargent** [comment]
I make no attempts to keep this cheat sheet specifically aligned with any particular version of Docker, and I'm not versioning or tagging it to specific Docker versions.  I can't diff all of the Docker documentation on every release: I rely on contributors to keep me updated when things change between versions, and I don't want to have to backport any documentation.  What you see is what you get.
